PreCommit:
  Brakeman:
    enabled: true
  HardTabs:
    enabled: true
  HtmlHint:
    enabled: true
  ImageOptim:
    enabled: true
  Jscs:
    enabled: true
  JsHint:
    enabled: true
  MergeConflicts:
    enabled: true
  RuboCop:
    enabled: true
  ScssLint:
    enabled: true
  TrailingWhitespace:
    enabled: true
  W3cHtml:
    enabled: true
